# Generated by Django 3.2 on 2022-03-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorprofile', '0003_auto_20220328_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
