# Generated by Django 3.2 on 2022-03-28 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorprofile', '0004_booking_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_approved',
        ),
    ]
