# Generated by Django 3.2 on 2022-04-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorprofile', '0007_rename_reviews_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='slug',
        ),
    ]
