# Generated by Django 3.2 on 2022-04-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorprofile', '0009_alter_review_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='tutor',
            field=models.CharField(choices=[('tutor_one', 'Barry Hyman'), ('tutor_two', 'Jennifer Roberts'), ('tutor_three', 'Mark Macintosh')], default='tutor_one', max_length=20),
        ),
    ]
