# Generated by Django 3.2 on 2022-04-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorprofile', '0012_alter_booking_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='status',
        ),
    ]
