# Generated by Django 3.2 on 2022-02-23 15:20

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('year_group', models.CharField(choices=[('year_7', 'YEAR_7'), ('year_8', 'YEAR_8'), ('year_9', 'YEAR_9'), ('year_10', 'YEAR_10'), ('year_11', 'YEAR_11')], default='year_7', max_length=7)),
                ('about_me', models.TextField()),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_page', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
