# Generated by Django 3.2 on 2022-04-12 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_userprofile_science'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='current_grade',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='predicted_grade',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='science',
        ),
    ]
