# Generated by Django 3.2 on 2022-04-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_auto_20220412_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='english',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='maths',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='science',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
