# Generated by Django 3.2 on 2022-05-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_auto_20220412_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='surname',
        ),
    ]
